Add dbcheck to start.sh

diff --git a/taiga-back/start b/taiga-back/start
--- a/taiga-back/start
+++ b/taiga-back/start
@@ -4,14 +4,40 @@ bash /usr/local/taiga/configure
 
 cd /usr/local/taiga/taiga-back/
 
-python manage.py collectstatic --noinput
+# Sleep when asked to, to allow the database time to start
+# before Taiga tries to run /checkdb.py below.
+: ${TAIGA_SLEEP:=0}
+sleep $TAIGA_SLEEP
+
+# Setup database automatically if needed
+if [ -z "$TAIGA_SKIP_DB_CHECK" ]; then
+  python /checkdb.py
+  DB_CHECK_STATUS=$?
+
+  if [ $DB_CHECK_STATUS -eq 1 ]; then
+    echo "Failed to connect to database server."
+    exit 1
+  elif [ $DB_CHECK_STATUS -eq 2 ]; then
+    echo "Configuring initial database"
+    python manage.py migrate --noinput
+    python manage.py loaddata initial_user
+    python manage.py loaddata initial_project_templates
+    python manage.py loaddata initial_role
+    python manage.py compilemessages
+  fi
+fi
+
+# Look for static folder, if it does not exist, then generate it
+if [ "$(ls -A /usr/local/taiga/static)" ]; then
+   echo "Static files already exist, SKIP"
+else
+   python manage.py collectstatic --noinput
+fi
 
 echo "Waiting for Postgresql to be available..."
 while ! nc -z $POSTGRES_PORT_5432_TCP_ADDR 5432; do
   sleep 1
 done
-
-python manage.py migrate --noinput
 
 chown -R taiga /usr/local/taiga/media /usr/local/taiga/static /usr/local/taiga/logs
 
